INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [25/Jul/2022 20:21:20] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Jul/2022 20:21:20] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:root:выполняю поиск
INFO:werkzeug:127.0.0.1 - - [25/Jul/2022 20:21:21] "GET /search/?s= HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Jul/2022 20:21:21] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [25/Jul/2022 20:21:21] "[36mGET /uploads/images/IMG_8938.JPG HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [25/Jul/2022 20:21:21] "[36mGET /uploads/images/dl77uuQWIpU.jpg HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [25/Jul/2022 20:22:15] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Jul/2022 20:22:15] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
ERROR:app:Exception on /search/ [GET]
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\hm12\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\sasha\PycharmProjects\hm12\venv\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\sasha\PycharmProjects\hm12\venv\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\sasha\PycharmProjects\hm12\venv\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\sasha\PycharmProjects\hm12\lesson12_project_source_v3\main\main.py", line 17, in get_posts_page
    logging.info("выполняю поиск",encoding = "UTF-8")
  File "C:\Users\sasha\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 2138, in info
    root.info(msg, *args, **kwargs)
  File "C:\Users\sasha\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
TypeError: Logger._log() got an unexpected keyword argument 'encoding'
INFO:werkzeug:127.0.0.1 - - [25/Jul/2022 20:25:12] "[35m[1mGET /search/?s= HTTP/1.1[0m" 500 -
ERROR:app:Exception on /search/ [GET]
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\hm12\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\sasha\PycharmProjects\hm12\venv\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\sasha\PycharmProjects\hm12\venv\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\sasha\PycharmProjects\hm12\venv\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\sasha\PycharmProjects\hm12\lesson12_project_source_v3\main\main.py", line 17, in get_posts_page
    logging.info("выполняю поиск",encoding = "UTF-8")
  File "C:\Users\sasha\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 2138, in info
    root.info(msg, *args, **kwargs)
  File "C:\Users\sasha\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
TypeError: Logger._log() got an unexpected keyword argument 'encoding'
INFO:werkzeug:127.0.0.1 - - [25/Jul/2022 20:25:15] "[35m[1mGET /search/?s= HTTP/1.1[0m" 500 -
ERROR:app:Exception on /search/ [GET]
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\hm12\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\sasha\PycharmProjects\hm12\venv\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\sasha\PycharmProjects\hm12\venv\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\sasha\PycharmProjects\hm12\venv\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\sasha\PycharmProjects\hm12\lesson12_project_source_v3\main\main.py", line 17, in get_posts_page
    logging.info("выполняю поиск",encoding = "UTF-8")
  File "C:\Users\sasha\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 2138, in info
    root.info(msg, *args, **kwargs)
  File "C:\Users\sasha\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
TypeError: Logger._log() got an unexpected keyword argument 'encoding'
INFO:werkzeug:127.0.0.1 - - [25/Jul/2022 20:25:18] "[35m[1mGET /search/?s=f HTTP/1.1[0m" 500 -
ERROR:app:Exception on /search/ [GET]
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\hm12\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\sasha\PycharmProjects\hm12\venv\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\sasha\PycharmProjects\hm12\venv\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\sasha\PycharmProjects\hm12\venv\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\sasha\PycharmProjects\hm12\lesson12_project_source_v3\main\main.py", line 17, in get_posts_page
    logging.info("выполняю поиск",encoding = "UTF-8")
  File "C:\Users\sasha\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 2138, in info
    root.info(msg, *args, **kwargs)
  File "C:\Users\sasha\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
TypeError: Logger._log() got an unexpected keyword argument 'encoding'
INFO:werkzeug:127.0.0.1 - - [25/Jul/2022 20:25:22] "[35m[1mGET /search/?s=фотка HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:root:РІС‹РїРѕР»РЅСЏСЋ РїРѕРёСЃРє
INFO:werkzeug:127.0.0.1 - - [25/Jul/2022 20:27:20] "GET /search/?s=С„РѕС‚РєР° HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Jul/2022 20:27:20] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
